### ISSUE TITLE
All finished surveys are evaluated as `BEST` regardless

### ISSUE THREAD

**Issue by stanzheng** [Code4HR/okcandidate#205]
It might be with how answered and question state is populated.

from #200 its mentioned that getMatchLevel, answered questioned and total questions is `(0,0)`

**Comment by wbprice** [comment]
The number of questions and questions answered are both initialized to zero.  Because the rating is determined by the percentage of questions answered / questions that exist, it follows that (temporarily) the rating is perfect while the questions are still being fetched.  Write a special case for the indicator where the rating is :( while the number of questions is still 0.

**Comment by stanzheng** [comment]
so another case? what would you suggest the heart level and the copy be then for the `survey complete` case.

**Comment by wbprice** [comment]
If the survey is complete (questions exist, and they have all been answered), that should be `BEST`
