### ISSUE TITLE
User information stored in database needs to be encrypted

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#220]

**Comment by stanzheng** [comment]
I been suggesting a shorter circuit is from here

https://github.com/Code4HR/okcandidate/blob/develop/api/controllers/SurveyResponse.js#L8-L11

we could anonymize this by replacing the emails Survey with 
`voter@okcandidate.org` or `757-555-555` before its returned since no one will ever have to get it out. 

I suggested to @ttavenner we could directly query postgres or just do a one time CSV dump when we want to send the alert on May 5th with @MFogleman
