### ISSUE TITLE
Skip answered question is confusing.

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/okcandidate#79]
If I answer a question and rate it with hearts the only option I have is to "Skip" or "Submit".
![screen shot 2016-04-06 at 9 48 16 pm](https://cloud.githubusercontent.com/assets/69151/14338573/0984e30a-fc46-11e5-85ff-52916f63036b.png)

**Comment by kmcurry** [comment]
Submit might be easy to press by mistake, too.

**Comment by stanzheng** [comment]
what would the expected or recommended behavior be? 

Would it be better if after the question is answered the first time completely, it transitions to the next question.  So we leave the options of just `BACK` and `SKIP`

**Comment by kmcurry** [comment]
I'm not sure but I think auto-advance after answer + rate would work well.
That way the buttons as they are make perfect sense. If it advances before
the user is ready they hit Back. If the user doesn't click either an answer
or a rating the survey stays on the question unless the user hits skip. In
that case we still capture whichever item they may have clicked.

On Wed, Apr 6, 2016 at 10:58 PM, Stanley Zheng <notifications@github.com>
wrote:

> what would the expected or recommended behavior be?
>
> Would it be better if after the question is answered the first time
> completely, it transitions to the next question. So we leave the options of
> just BACK and SKIP
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Code4HR/okcandidate/issues/79#issuecomment-206672568>
>



-- 
Kevin Curry
Virginia Beach, VA
https://comparityins.com

**Comment by wbprice** [comment]
I think we can still iterate on this, but this is what is happening right now in master: 
<img width="352" alt="screen shot 2016-04-10 at 11 56 44 pm" src="https://cloud.githubusercontent.com/assets/2590422/14416424/f9041d4a-ff77-11e5-8344-b4a648421e57.png">
1. Back button goes to the previous question. If on the first question, goes to the front page.
2. Next button goes to the next question.  If one of the two options is not filled out, the user gets appropriate messaging.  Otherwise, if they haven't interacted with the form, it's a defacto skip.  Once the user has gone through all the questions, the results page is displayed.

**Comment by wbprice** [comment]
Resolved in master.
